"""Type stubs for the eggress native extension module (_eggress)."""

from __future__ import annotations

from typing import Any, Sequence

__version__: str

class EggressError(Exception): ...
class ConfigError(EggressError): ...
class StartupError(EggressError): ...
class ReloadError(EggressError): ...
class ShutdownError(EggressError): ...
class UnsupportedFeatureError(EggressError): ...
class InternalError(EggressError): ...
class ConnectionError(EggressError): ...
class ConnectionClosedError(EggressError): ...
class TimeoutError(EggressError): ...
class DnsError(EggressError): ...
class AuthError(EggressError): ...
class TlsError(EggressError): ...
class LoopMismatchError(EggressError): ...
class ConnectionCancelledError(EggressError): ...
class UseAfterCloseError(EggressError): ...
class UdpAssociationError(EggressError): ...
class UnsupportedCompositionError(EggressError): ...

class PyEggressConfig:
    @staticmethod
    def from_toml(toml_str: str) -> PyEggressConfig: ...
    @staticmethod
    def from_file(path: str) -> PyEggressConfig: ...
    def redacted_toml(self) -> str: ...

class PyEggressService:
    def __init__(self, config: PyEggressConfig) -> None: ...
    @staticmethod
    def from_toml(toml_str: str) -> PyEggressService: ...
    @staticmethod
    def from_file(path: str) -> PyEggressService: ...
    def start(self) -> PyEggressHandle: ...

class PyEggressHandle:
    def bound_addresses(self) -> dict[str, str]: ...
    def status(self) -> dict[str, Any]: ...
    def metrics_text(self) -> str: ...
    def reload_toml(self, toml_str: str) -> dict[str, Any]: ...
    def shutdown(self) -> None: ...
    def __enter__(self) -> PyEggressHandle: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class PyUriInfo:
    @property
    def scheme(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def tls(self) -> bool: ...
    @property
    def ssl(self) -> bool: ...
    @property
    def inbound(self) -> bool: ...
    @property
    def backward_num(self) -> int: ...
    @property
    def has_auth(self) -> bool: ...
    @property
    def has_rule(self) -> bool: ...
    @property
    def is_reverse_listener(self) -> bool: ...
    @property
    def redacted_display(self) -> str: ...
    @property
    def error(self) -> str | None: ...

class PyDiagnostic:
    @property
    def code(self) -> str: ...
    @property
    def feature_id(self) -> str | None: ...
    @property
    def tier(self) -> str | None: ...
    @property
    def message(self) -> str: ...
    @property
    def suggestion(self) -> str | None: ...

class PyTranslationWarning:
    @property
    def category(self) -> str: ...
    @property
    def message(self) -> str: ...

class PyUnsupportedFeature:
    @property
    def feature(self) -> str: ...
    @property
    def message(self) -> str: ...

class PyTranslationResult:
    @property
    def toml(self) -> str: ...
    @property
    def warnings(self) -> list[PyTranslationWarning]: ...
    @property
    def unsupported(self) -> list[PyUnsupportedFeature]: ...
    @property
    def ok(self) -> bool: ...
    def config(self) -> PyEggressConfig: ...

class PyReverseUriSummary:
    @property
    def role(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def target(self) -> str: ...
    @property
    def has_auth(self) -> bool: ...
    @property
    def toml_section(self) -> str: ...
    @property
    def tls(self) -> bool: ...
    @property
    def modifiers(self) -> list[str]: ...

def translate_pproxy_args(args: Sequence[str]) -> PyTranslationResult: ...
def translate_pproxy_uri(local: str, remotes: Sequence[str] | None = None) -> PyTranslationResult: ...
def check_pproxy_args(args: Sequence[str]) -> PyTranslationResult: ...
def check_pproxy_uri(uri: str) -> PyUriInfo: ...
def redact_pproxy_uri(uri: str) -> str: ...
def diagnostics_for_uri(uri: str) -> list[PyDiagnostic]: ...
def supported_features() -> list[str]: ...
def describe_reverse_pproxy_uri(uri: str) -> PyReverseUriSummary: ...
def explain_config_toml(toml_str: str) -> dict[str, Any]: ...
def explain_pproxy_args(args: Sequence[str]) -> dict[str, Any]: ...
def explain_pproxy_uri(uri: str) -> dict[str, Any]: ...
def route_explain(toml_str: str, target: str) -> dict[str, Any]: ...
def test_upstream_connect(uri: str, timeout_secs: float) -> dict[str, Any]: ...

class PyConnection:
    def __init__(self, uris: list[str]) -> None: ...
    @property
    def state(self) -> str: ...
    @property
    def closed(self) -> bool: ...
    @property
    def config(self) -> str: ...
    @property
    def peername(self) -> str | None: ...
    @property
    def sockname(self) -> str | None: ...
    def extra_info(self) -> dict[str, Any]: ...
    def close(self) -> None: ...
    def wait_closed(self) -> None: ...
    @staticmethod
    def connection_stats() -> dict[str, int]: ...
    @staticmethod
    def reset_connection_stats() -> None: ...
