"""Type stubs for eggress.cipher module."""

from __future__ import annotations

from typing import Any, Optional, Tuple

class BaseCipher:
    KEY_LENGTH: int
    IV_LENGTH: int
    PYTHON: bool
    def __init__(self, key: bytes | str, ota: bool = ..., setup_key: bool = ...) -> None: ...
    @property
    def key(self) -> bytes: ...
    @property
    def iv(self) -> Optional[bytes]: ...
    def setup_iv(self, iv: Optional[bytes] = ...) -> None: ...
    def encrypt(self, s: bytes) -> bytes: ...
    def decrypt(self, s: bytes) -> bytes: ...
    @classmethod
    def name(cls) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[type[BaseCipher], tuple[bytes]]: ...
    def __copy__(self) -> BaseCipher: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> BaseCipher: ...

class AEADCipher(BaseCipher):
    NONCE_LENGTH: int
    TAG_LENGTH: int
    PACKET_LIMIT: int
    @property
    def nonce(self) -> bytes: ...
    def setup_nonce(self, nonce: Optional[bytes] = ...) -> None: ...
    def encrypt_chunk(self, data: bytes) -> bytes: ...
    def decrypt_chunk(self, data: bytes) -> bytes: ...
    def encrypt_and_digest(self, buffer: bytes) -> tuple[bytes, bytes]: ...
    def decrypt_and_verify(self, buffer: bytes, tag: bytes) -> bytes: ...

class AES_256_GCM_Cipher(AEADCipher): ...
class AES_192_GCM_Cipher(AEADCipher): ...
class AES_128_GCM_Cipher(AEADCipher): ...
class ChaCha20_IETF_POLY1305_Cipher(AEADCipher): ...

class RC4_Cipher(BaseCipher): ...
class RC4_MD5_Cipher(BaseCipher): ...
class ChaCha20_Cipher(BaseCipher): ...
class ChaCha20_IETF_Cipher(BaseCipher): ...
class Salsa20_Cipher(BaseCipher): ...
class AES_256_CFB_Cipher(BaseCipher): ...
class AES_192_CFB_Cipher(BaseCipher): ...
class AES_128_CFB_Cipher(BaseCipher): ...
class AES_256_CFB8_Cipher(BaseCipher): ...
class AES_192_CFB8_Cipher(BaseCipher): ...
class AES_128_CFB8_Cipher(BaseCipher): ...
class AES_256_OFB_Cipher(BaseCipher): ...
class AES_192_OFB_Cipher(BaseCipher): ...
class AES_128_OFB_Cipher(BaseCipher): ...
class AES_256_CTR_Cipher(BaseCipher): ...
class AES_192_CTR_Cipher(BaseCipher): ...
class AES_128_CTR_Cipher(BaseCipher): ...
class BF_CFB_Cipher(BaseCipher): ...
class CAST5_CFB_Cipher(BaseCipher): ...
class DES_CFB_Cipher(BaseCipher): ...

class PacketCipher:
    @property
    def cipher(self) -> BaseCipher: ...
    @property
    def key(self) -> bytes: ...
    @property
    def name(self) -> str: ...
    def __init__(self, cipher: BaseCipher, key: bytes | str, name: str) -> None: ...
    def encrypt(self, data: bytes) -> bytes: ...
    def decrypt(self, data: bytes) -> bytes: ...

MAP: dict[str, type[BaseCipher]]

class _ApplyCipher:
    @property
    def cipher(self) -> BaseCipher: ...
    @property
    def key(self) -> bytes: ...
    @property
    def name(self) -> str: ...
    @property
    def ota(self) -> bool: ...
    @property
    def plugins(self) -> list[Any]: ...
    @property
    def datagram(self) -> Optional[PacketCipher]: ...
    def __call__(self, data: bytes) -> bytes: ...

def get_cipher(cipher_key: str) -> Tuple[Optional[str], Optional[_ApplyCipher]]: ...
