"""Type stubs for the eggress.exceptions module."""

from eggress._eggress import (
    EggressError,
    ConfigError,
    StartupError,
    ReloadError,
    ShutdownError,
    UnsupportedFeatureError,
    InternalError,
    ConnectionError as ConnectionBaseError,
    ConnectionClosedError,
    TimeoutError as ConnectionTimeoutError,
    DnsError as ConnectionDnsError,
    AuthError as ConnectionAuthError,
    TlsError as ConnectionTlsError,
    LoopMismatchError,
    ConnectionCancelledError,
    UseAfterCloseError,
    UdpAssociationError,
    UnsupportedCompositionError,
)
from eggress.pproxy import AlreadyStartedError

__all__ = [
    "AlreadyStartedError",
    "EggressError",
    "ConfigError",
    "StartupError",
    "ReloadError",
    "ShutdownError",
    "UnsupportedFeatureError",
    "InternalError",
    "ConnectionBaseError",
    "ConnectionClosedError",
    "ConnectionTimeoutError",
    "ConnectionDnsError",
    "ConnectionAuthError",
    "ConnectionTlsError",
    "LoopMismatchError",
    "ConnectionCancelledError",
    "UseAfterCloseError",
    "UdpAssociationError",
    "UnsupportedCompositionError",
]
