"""Type stubs for eggress.plugin module."""

from __future__ import annotations

import asyncio
import threading
from dataclasses import dataclass
from typing import Any, Callable, Optional

class PluginError(Exception): ...
class PluginTimeoutError(PluginError): ...
class PluginRejectedError(PluginError): ...
class PluginShutdownError(PluginError): ...
class PluginReentrantError(PluginError): ...

HOOK_ON_PROTOCOL_DETECT: str
HOOK_ON_CIPHER_SELECT: str
HOOK_ON_CONNECT: str
HOOK_ON_DATA: str
BUILTIN_HOOKS: tuple[str, ...]

@dataclass(frozen=True)
class CallbackResult:
    hook_name: str
    value: Any
    elapsed_ms: float
    timed_out: bool = ...
    rejected: bool = ...
    error: Optional[str] = ...
    @property
    def ok(self) -> bool: ...

@dataclass
class CallbackMetrics:
    total: int = ...
    succeeded: int = ...
    failed: int = ...
    timed_out: int = ...
    rejected: int = ...
    total_elapsed_ms: float = ...
    @property
    def avg_elapsed_ms(self) -> float: ...
    def record(self, result: CallbackResult) -> None: ...

class CallbackWrapper:
    def __init__(self, callback: Callable[..., Any], timeout: float = ..., hook_name: str = ...) -> None: ...
    @property
    def hook_name(self) -> str: ...
    @property
    def timeout(self) -> float: ...
    @property
    def metrics(self) -> CallbackMetrics: ...
    async def execute(self, args: tuple[Any, ...], kwargs: dict[str, Any], timeout: Optional[float] = ...) -> CallbackResult: ...

class PluginRegistry:
    def __init__(self) -> None: ...
    def register(self, name: str, callback: Callable[..., Any], timeout: float = ...) -> None: ...
    def unregister(self, name: str) -> bool: ...
    def get(self, name: str) -> Optional[Callable[..., Any]]: ...
    def get_wrapper(self, name: str) -> Optional[CallbackWrapper]: ...
    def has(self, name: str) -> bool: ...
    def list_hooks(self) -> list[str]: ...
    def clear(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __repr__(self) -> str: ...

class PluginBridge:
    def __init__(self, registry: Optional[PluginRegistry] = ..., max_queue: int = ..., default_timeout: float = ...) -> None: ...
    @property
    def registry(self) -> PluginRegistry: ...
    @property
    def max_queue(self) -> int: ...
    @property
    def default_timeout(self) -> float: ...
    @property
    def active_count(self) -> int: ...
    @property
    def is_shutdown(self) -> bool: ...
    def metrics(self) -> dict[str, dict[str, Any]]: ...
    def submit(self, hook_name: str, *args: Any, timeout: Optional[float] = ..., **kwargs: Any) -> Any: ...
    async def submit_async(self, hook_name: str, *args: Any, timeout: Optional[float] = ..., **kwargs: Any) -> Any: ...
    def shutdown(self) -> None: ...
    def __repr__(self) -> str: ...
