"""Type stubs for the eggress.service module."""

from __future__ import annotations

from os import PathLike
from typing import Any, Optional, Sequence, Union

from eggress.config import EggressConfig

class EggressService:
    def __init__(self, config: EggressConfig) -> None: ...
    @classmethod
    def from_toml(cls, toml: str) -> EggressService: ...
    @classmethod
    def from_file(cls, path: Union[str, PathLike[str]]) -> EggressService: ...
    @classmethod
    def from_pproxy_args(cls, args: Sequence[str], allow_partial: bool = False) -> EggressService: ...
    def start(self) -> EggressHandle: ...
    async def astart(self) -> AsyncEggressHandle: ...

class EggressHandle:
    @property
    def bound_addresses(self) -> dict[str, str]: ...
    def status(self) -> dict[str, Any]: ...
    def metrics_text(self) -> str: ...
    def reload_toml(self, toml: str) -> dict[str, Any]: ...
    def shutdown(self) -> None: ...
    def __enter__(self) -> EggressHandle: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: Any) -> bool: ...

class AsyncEggressHandle:
    async def bound_addresses(self) -> dict[str, str]: ...
    async def status(self) -> dict[str, Any]: ...
    async def metrics_text(self) -> str: ...
    async def reload_toml(self, toml: str) -> dict[str, Any]: ...
    async def shutdown(self) -> None: ...
    async def __aenter__(self) -> AsyncEggressHandle: ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: Any) -> bool: ...

PPProxyHandle = EggressHandle
