"""Type stubs for eggress.wrapper module."""

from __future__ import annotations

from typing import Any

class BaseWrapper:
    _WRAP_TYPE: str
    def __init__(self, inner: Any) -> None: ...
    @property
    def inner(self) -> Any: ...
    @property
    def name(self) -> str: ...
    @property
    def target(self) -> str | None: ...
    @property
    def dest(self) -> str | None: ...
    @property
    def source(self) -> str | None: ...
    @property
    def _SUPPORTED_IN_EGRESS(self) -> bool: ...
    @property
    def _TRAFFIC_KINDS(self) -> tuple[str, ...]: ...
    @property
    def _ROLE(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[Any, tuple[Any]]: ...
    def __copy__(self) -> BaseWrapper: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> BaseWrapper: ...

class TLS(BaseWrapper):
    _WRAP_TYPE: str
    def __init__(
        self,
        inner: Any,
        certfile: str | None = ...,
        keyfile: str | None = ...,
        sni: str | None = ...,
    ) -> None: ...
    @property
    def certfile(self) -> str | None: ...
    @property
    def keyfile(self) -> str | None: ...
    @property
    def sni(self) -> str | None: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[Any, tuple[Any, str | None, str | None, str | None]]: ...
    def __copy__(self) -> TLS: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> TLS: ...

class Plugin(BaseWrapper):
    _WRAP_TYPE: str
    def __init__(self, inner: Any, handler: Any | None = ...) -> None: ...
    @property
    def handler(self) -> Any | None: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __reduce__(self) -> tuple[Any, tuple[Any, Any | None]]: ...
    def __copy__(self) -> Plugin: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> Plugin: ...

class Chain:
    protocols: tuple[Any, ...]
    def __init__(self, protocols: list[Any]) -> None: ...
    @property
    def target(self) -> str | None: ...
    @property
    def dest(self) -> str | None: ...
    @property
    def source(self) -> str | None: ...
    @property
    def name(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __iter__(self) -> Any: ...
    def __contains__(self, item: Any) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def flat(self) -> list[Any]: ...
    def validate(self) -> list[str]: ...
    def __reduce__(self) -> tuple[Any, tuple[list[Any]]]: ...
    def __copy__(self) -> Chain: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> Chain: ...

def normalize_chain(protocols: list[Any]) -> Chain: ...
