[package]
name = "eggress-protocol-shadowsocks"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Shadowsocks protocol implementation for eggress"

[features]
default = []
pproxy-legacy = ["dep:flate2"]
legacy-crypto = [
    "dep:aes",
    "dep:blowfish",
    "dep:camellia",
    "dep:chacha20",
    "dep:des",
    "dep:hmac",
    "dep:salsa20",
]

[dependencies]
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
bytes.workspace = true
eggress-core.workspace = true
eggress-uri.workspace = true
aes-gcm = "0.10"
chacha20poly1305 = "0.10"
hkdf = "0.12"
sha2 = "0.10"
sha1 = "0.10"
md-5 = "0.10"
rand = "0.8"
flate2 = { workspace = true, optional = true }
aes = { version = "0.8", optional = true }
blowfish = { version = "0.10", optional = true }
camellia = { version = "0.1", optional = true }
chacha20 = { version = "0.9", optional = true }
des = { version = "0.8", optional = true }
hmac = { version = "0.12", optional = true }
salsa20 = { version = "0.11", optional = true }

[dev-dependencies]
tokio.workspace = true
eggress-testkit.workspace = true

[lints]
workspace = true
