[package]
name = "eggress-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "TOML configuration and validation for eggress proxy"
keywords = ["proxy", "config", "toml"]
categories = ["config"]
readme = "README.md"

[features]
default = []
quic = []

[dependencies]
eggress-core.workspace = true
eggress-udp.workspace = true
eggress-uri.workspace = true
eggress-routing.workspace = true
eggress-transport-tls.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true
thiserror.workspace = true
regex.workspace = true
ipnet.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true
rcgen = "0.13"

[lints]
workspace = true
