[package]
name = "eggress-server"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["full"]
full = ["extended"]
common = []
extended = [
    "dep:eggress-protocol-shadowsocks",
    "dep:eggress-protocol-trojan",
    "dep:eggress-protocol-websocket",
    "eggress-udp/shadowsocks",
]
pproxy-legacy = ["extended", "eggress-protocol-shadowsocks/pproxy-legacy"]
legacy-crypto = ["extended", "eggress-protocol-shadowsocks/legacy-crypto"]
ssh = ["dep:eggress-transport-ssh"]
quic = ["dep:eggress-transport-quic", "dep:eggress-protocol-h3"]

[dev-dependencies]
eggress-testkit.workspace = true
futures-util.workspace = true
tokio-tungstenite.workspace = true
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "net", "io-util", "test-util"] }

[dependencies]
eggress-core.workspace = true
eggress-uri.workspace = true
eggress-routing.workspace = true
eggress-protocol-http.workspace = true
eggress-protocol-socks.workspace = true
eggress-protocol-shadowsocks = { workspace = true, optional = true }
eggress-protocol-trojan = { workspace = true, optional = true }
eggress-protocol-websocket = { workspace = true, optional = true }
bytes.workspace = true
h2.workspace = true
http.workspace = true
eggress-transport-tls.workspace = true
eggress-transport-ssh = { workspace = true, optional = true }
eggress-transport-quic = { workspace = true, optional = true }
eggress-protocol-h3 = { workspace = true, optional = true }
eggress-udp.workspace = true
rustls.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
thiserror.workspace = true
subtle.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[lints]
workspace = true
