[package]
name = "eggress-transport-quic"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
bytes.workspace = true
eggress-core.workspace = true
h3.workspace = true
h3-quinn.workspace = true
quinn.workspace = true
rustls.workspace = true
rustls-platform-verifier.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
rcgen.workspace = true

[lints]
workspace = true
