[package]
name = "eggress-protocol-socks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "SOCKS4/4a and SOCKS5 protocol for eggress proxy"
keywords = ["proxy", "socks", "socks4", "socks5"]
categories = ["network-programming"]
readme = "README.md"

[dependencies]
eggress-core.workspace = true
bytes.workspace = true
thiserror.workspace = true
tokio.workspace = true
subtle.workspace = true
zeroize.workspace = true

[dev-dependencies]
eggress-testkit.workspace = true
proptest.workspace = true

[lints]
workspace = true
